### ISSUE TITLE
Infinispan Distributed mode clustered-cache-quickstart

### ISSUE THREAD

**Issue by DonatasD** [infinispan/infinispan-quickstart#25]
Hello everyone I am new to Infinispan and I have some questions in regards to distributed mode and quickstarts provided in https://github.com/infinispan  in particular clustered-cache-quickstart.

First of all, as far as I understand distributed mode allows to have defined number of entry copies rather than replicated mode, which replicates entries within all nodes. For example, if we had 3 entries (1, 2, 3) and 3 caches (A, B, C) where numOwners(2) the resulting view of cluster in distributed mode might result as: A containing 1,2 B containing 2,3 C containing 3,1 Where replicated mode cluster would result in: A,B and C containing 1,2,3 Please correct me if my assumption is wrong.

What is more, then I run https://github.com/infinispan/infinispan-quickstart/tree/master/clustered-cache this quickstart using these instructions

To try with a distributed cache, run the following command in separated terminals:

Terminal 1

mvn compile exec:java -Djava.net.preferIPv4Stack=true -Dexec.mainClass="org.infinispan.quickstart.clusteredcache.Node" -Dexec.args="-d A"
Terminal 2

mvn compile exec:java -Djava.net.preferIPv4Stack=true -Dexec.mainClass="org.infinispan.quickstart.clusteredcache.Node" -Dexec.args="-d B"
Terminal 3

mvn compile exec:java -Djava.net.preferIPv4Stack=true -Dexec.mainClass="org.infinispan.quickstart.clusteredcache.Node" -Dexec.args="-d C"
All my nodes result in having the same entries (I limited entry number to 10) :

Node A

    Cache contents on node A-29339
    key-0 = A-29339-0
    key-1 = A-29339-1
    key-2 = A-29339-2
    key-3 = A-29339-3
    key-4 = A-29339-4
    key-5 = A-29339-5
    key-6 = A-29339-6
    key-7 = A-29339-7
    key-8 = A-29339-8
    key-9 = A-29339-9
Node B

    Cache contents on node B-36604
    key-0 = A-29339-0
    key-1 = A-29339-1
    key-2 = A-29339-2
    key-3 = A-29339-3
    key-4 = A-29339-4
    key-5 = A-29339-5
    key-6 = A-29339-6
    key-7 = A-29339-7
    key-8 = A-29339-8
    key-9 = A-29339-9
Node C

    Cache contents on node C-26839
    key-0 = A-29339-0
    key-1 = A-29339-1
    key-2 = A-29339-2
    key-3 = A-29339-3
    key-4 = A-29339-4
    key-5 = A-29339-5
    key-6 = A-29339-6
    key-7 = A-29339-7
    key-8 = A-29339-8
    key-9 = A-29339-9
However, in the documentation http://infinispan.org/docs/7.1.x/getting_started/getting_started.html#_distributed_mode it said that: You can also see that each node holds a different set of entries by pressing Enter. Nevertheless, my output shows that all entries are basically replicated as would be done in replicated mode. Any ideas why this is happening like this?

**Comment by galderz** [comment]
Maybe the arguments are not being passed correctly? If `-d` is not processed correctly, it would default on replicated cache. You can try to run the class from an IDE and debug through it, or you could add `-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=y` to the JVM parameters of the Maven execution and then hook a remote debugger from the IDE to see what's up.

**Comment by DonatasD** [comment]
I put this question on the forum as well. Here is the answer and fix for the problem I mentioned before.
https://developer.jboss.org/thread/257293?sr=stream

**Comment by galderz** [comment]
Oh good, closing then :)
